### ISSUE TITLE
Evaluate if can use docker swarm / stack deploy and Kubernetes

### ISSUE THREAD

**Issue by puneet-khushwani-eth** [mosaicdao/mosaic-chains#253]
These could potentially help in making our docker processes more fault tolerant 

https://docs.docker.com/engine/reference/commandline/stack_deploy/
https://docs.docker.com/engine/swarm/
https://kubernetes.io/

**Comment by puneet-khushwani-eth** [comment]
This article very well summarises what I read about these two technologies.

https://hackernoon.com/kubernetes-vs-docker-swarm-a-comprehensive-comparison-73058543771e

To summarise, both these solutions can help us monitor desired state of a cluster and act accordingly if things go wrong to bring it back to work.

Kubernetes seems to be superior and stronger market competitor today but also is a bit more complex to get started with. 

Getting into a bit of implementation details, haven't got chance to make it work yet.

1. Using `kubectl` API

`kubectl create deployment hello-node --image=gcr.io/hello-minikube-zero-install/hello-node`
`kubectl expose deployment hello-node --type=LoadBalancer --port=8080`
`kubectl scale --replicas=3 deployment/hello-node`

ref: 
https://rominirani.com/tutorial-getting-started-with-kubernetes-with-docker-on-mac-7f58467203fd
https://kubernetes.io/docs/tutorials/hello-minikube/

2. Docker itself supports both of these orchestration frameworks via the `stack` command.

`docker stack deploy --compose-file /path/to/docker-compose.yml mystack`

`stack deploy` start's all services and `stack rm` stop services in the stack. 

ref: 
https://docs.docker.com/engine/reference/commandline/stack_deploy/
https://docs.docker.com/docker-for-mac/kubernetes/
https://medium.com/@Grigorkh/docker-for-beginners-part-4-deploying-an-app-to-a-swarm-620b4d67e7c3

**Comment by puneet-khushwani-eth** [comment]
did a small POC by starting a local node for Kubernetes (using Docker Desktop) and by changing our compose file to below

```
version: '3'
services:
  graph-node:
    image: graphprotocol/graph-node:v0.16.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
    depends_on:
      - ipfs
      - postgres
    environment:
      postgres_host: postgres:5432
      postgres_user: test
      postgres_pass: test
      postgres_db: test
      ipfs: 'ipfs:5001'
      ethereum: 'dev:http://127.0.0.1:41515'
      RUST_LOG: info
      GRAPH_LOG: info
      ETHEREUM_POLLING_INTERVAL: 3000
      ETHEREUM_REORG_THRESHOLD: 0
      RUST_BACKTRACE: 1
  ipfs:
    image: ipfs/go-ipfs:v0.4.22-rc1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - '5001:5001'
    volumes:
      - '/Users/puneetkhushwani/.mosaic/dev-origin/test/ipfs:/data/ipfs'
  postgres:
    image: postgres:alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    volumes:
      - '/Users/puneetkhushwani/.mosaic/dev-origin/test/postgres:/var/lib/postgresql/data'

```

`docker stack deploy --compose-file docker-compose.yml graph`  -> started 1 instance for all the 3 services (on a single node) and kubernetes process was spawning a fresh instance for one I was manually killing. 

`docker stack rm graph` -> stops all services
